[package]
name = "bvr_detect"
version = "0.2.0"
edition = "2021"

[lib]
name = "BvrDetect"
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]
#pyo3 = { version = "0.22.2", features = [ "auto-initialize"] }
ndarray = "0.16"
image = "0.25.2"
fast_image_resize = { version = "4.2.1", features = ["image"] }
tracing-subscriber = "0.3.18"
parking_lot = "0.12.3"
crossbeam-channel = "0.5.13"

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
anyhow = "1.0.87"
log = "0.4.22"
tracing = "0.1"

[dev-dependencies]
imageproc = "0.25.0"

[dependencies.ort]
version = "2.0.0-rc.6"
default-features = false
features = ["load-dynamic", "cuda", "tensorrt", "ndarray", "half"]
