[package]
name = "bvr_detect"
version = "0.2.0"
edition = "2021"

[lib]
name = "BvrDetect"
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]
ndarray = { version = "0.16", features = ["rayon"] }
image = "0.25.2"
fast_image_resize = { version = "5.0.0", features = ["image"] }
#tracing-subscriber = "0.3.18"
parking_lot = "0.12.3"
crossbeam-channel = "0.5.13"
half = { version = "2.4.1" }
rand = { version = "0.8.5" }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
anyhow = "1.0.87"
log = "0.4.22"
#tracing = "0.1"
rayon = "1.10.0"
prost = "0.13.3"
regex = "1.11.0"
dirs = "5.0.1"
#pyo3 = { version = "0.22.5", features = [ "auto-initialize"] }

[dependencies.ort]
version = "2.0.0-rc.6"
default-features = false
features = ["load-dynamic", "cuda", "tensorrt", "ndarray", "half"]

[dev-dependencies]
imageproc = "0.25.0"
ab_glyph = "0.2.29"

