[package]
name = "bvr_detect"
version = "0.2.0"
edition = "2021"

[lib]
name = "BvrDetect"
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]
expand = "0.3.0"
ort = { version = "2.0.0-rc.6", features = ["load-dynamic", "cuda", "tensorrt"] }
pyo3 = { version = "0.22.2", features = [ "auto-initialize"] }
ndarray = "0.16"
rand = "0.9.0-alpha.2"
serde_json = "1.0.128"
image = "0.25.2"
fast_image_resize = { version = "4.2.1", features = ["image"] }
tracing-subscriber = "0.3.18"
axum = "0.7"
parking_lot = "0.12.3"

ureq = "2.1"
tracing = "0.1"
anyhow = "1.0.87"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
which = "6.0.3"
